### ISSUE TITLE
add respondd vlan detection

### ISSUE THREAD

**Issue by mokkin** [freifunk-gluon/packages#150]
Unfortunately respondd seems to be not vlan aware. This produces incorrect data about the connection type for maps such as HopGlass. See also:
https://forum.freifunk.net/t/hopglass-development-thread/10984/116

**Comment by NeoRaider** [comment]
Unfortunately, this is the wrong repository, all respondd data providers are in the Gluon main repo. I've opened a ticket there: https://github.com/freifunk-gluon/gluon/issues/941

Please check if I correctly got that the issue is, there were many different questions in the forum thread you linked...
