### ISSUE TITLE
tunneldigger: Non-unique sessions forced to server by client

### ISSUE THREAD

**Issue by charlemagnelasse** [freifunk-gluon/packages#174]
The tunneldigger client in gluon is broken and doesn't allow unique sessions on the server. This causes to server to drop every tunneling attempt (except the first one). Patches to fix that were added to the client in https://github.com/wlanslovenija/tunneldigger/issues/57

**Comment by Adorfer** [comment]
please beware that server(s) and all clients have to be patched/corrected at the same time. 
Since up to now, a kernel "before" and "after" can not connect (except the first client)

So for the moment, on the server you have to stay at a kernel maximum 4.10.0-26 until someone comes up with a full blown case handling. 
Possibly it will be neccesary to setup a second server and do a migration by a firmware rollout, switching clients to the new L2TP server. 
(the [fix](https://github.com/linux-stable/linux-stable/commit/dbdbc73b44782e22b3b4b6e8b51e7a3d245f3086) has been backported to 4.10.0 as well)

**Comment by charlemagnelasse** [comment]
According to https://github.com/wlanslovenija/tunneldigger/issues/57, a new client can connect to an old server (and most likely also vice versa). Only when you run a new kernel on the broker, all clients most use the new software and the broker must be updated.

**Comment by lcb01a** [comment]
Created new pull requests:

v2017.1.x branch
https://github.com/freifunk-gluon/packages/pull/179

master branch:
https://github.com/freifunk-gluon/packages/pull/178

This also includes some newer commits which make use of the cmake system to build the client.

**Comment by RalfJung** [comment]
> A new client can connect to an old server (and most likely also vice versa). Only when you run a new kernel on the broker, all clients most use the new software and the broker must be updated.

Correct. The tunneldigger client and server are forwards and backwards compatible. The way we are rolling this out in Freifunk Saar is as follows:

* Rolling out new tunneldigger clients on the nodes and new tunneldigger brokers on the gateways can happen in parallel.
* Once most nodes have the new firmware, we can update most gateways' kernels.  This relies on us using usage-based broker selection -- the remaining old clients will be steered towards the remaining gateways with old kernels. This is the state we are in now.
* Once all nodes have the new firmware, all kernels can be updated. Starting now, every gateway can only have one "old-style" connection -- so, if an occasional outdated client comes along, it can still connect and then hopefully auto-update.

**Comment by rotanid** [comment]
fixed by #178 and #179 as far as i know. closing.
